// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0JXnWlj9eLh4H9rH07R99BJJ18tt1XJE',
    appId: '1:859138604903:web:00c6504e9affb16699b9c2',
    messagingSenderId: '859138604903',
    projectId: 'riaya-smart',
    authDomain: 'riaya-smart.firebaseapp.com',
    storageBucket: 'riaya-smart.firebasestorage.app',
    measurementId: 'G-43MQQHWZKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETWGVbbR5FnB3ED1L6oHZy4wyLt37LMQ',
    appId: '1:859138604903:android:7a93c815b191cba199b9c2',
    messagingSenderId: '859138604903',
    projectId: 'riaya-smart',
    storageBucket: 'riaya-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hhJqu4ltZ44qFMgdyh9Mscej8Cw8L5Y',
    appId: '1:859138604903:ios:b2ff47087eafd99199b9c2',
    messagingSenderId: '859138604903',
    projectId: 'riaya-smart',
    storageBucket: 'riaya-smart.firebasestorage.app',
    iosBundleId: 'com.example.riayasmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_hhJqu4ltZ44qFMgdyh9Mscej8Cw8L5Y',
    appId: '1:859138604903:ios:b2ff47087eafd99199b9c2',
    messagingSenderId: '859138604903',
    projectId: 'riaya-smart',
    storageBucket: 'riaya-smart.firebasestorage.app',
    iosBundleId: 'com.example.riayasmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0JXnWlj9eLh4H9rH07R99BJJ18tt1XJE',
    appId: '1:859138604903:web:a92572a490f1b13399b9c2',
    messagingSenderId: '859138604903',
    projectId: 'riaya-smart',
    authDomain: 'riaya-smart.firebaseapp.com',
    storageBucket: 'riaya-smart.firebasestorage.app',
    measurementId: 'G-JF98NC4901',
  );
}
